name: memq5-cudf
channels:
  - rapidsai
  - conda-forge
  - nvidia
  - nodefaults
dependencies:
  - python=3.11
  - cuda-version=12.6
  - arrow-cpp=23.0.1
  - pyarrow=23.0.1
  - cudf=26.06
  - cmake
  - ninja
  - openssl
  - nlohmann_json
  - pytest
  - psutil
