#!/usr/bin/env bash

set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

ALGO="PRVJ"
R_SIZE=$((1 << 24))
S_SIZE=$((1 << 30))
THREADS="${THREADS:-64}"
PAYLOAD_WIDTHS="${PAYLOAD_WIDTHS:-1 2 4}"
RADIX_BITS_LIST="${RADIX_BITS_LIST:-14 16 18}"
NUM_PASSES="${NUM_PASSES:-2}"
OUT="${OUT:-prvj-tuning-$(date -Iseconds).csv}"
LOG_DIR="${LOG_DIR:-prvj-tuning-logs-$(date -Iseconds)}"
BUILD_LOG="${BUILD_LOG:-prvj-tuning-build.log}"
BASIC_NUMA="${BASIC_NUMA:-1}"
KEY8B="${KEY8B:-0}"
RUN=0
ALLOW_GENERATED_OVERFLOW=0
R_FILE=""
S_FILE=""

usage() {
  cat <<EOF
Usage: $0 [--run] [options]

Default mode is dry-run: print the planned single-point PRVJ tuning matrix
without building or running long jobs. Pass --run to execute it.

Options:
  --run                         Execute the build/run matrix.
  --dry-run                     Print the plan only. This is the default.
  --threads N                   Thread count to use [${THREADS}].
  --r-size N                    Build relation cardinality [${R_SIZE}].
  --s-size N                    Probe relation cardinality [${S_SIZE}].
  --payload-widths "1 2 4"      Payload widths to scan [${PAYLOAD_WIDTHS}].
  --radix-bits "14 16 18"       NUM_RADIX_BITS candidates [${RADIX_BITS_LIST}].
  --num-passes N                NUM_PASSES to compile with [${NUM_PASSES}].
  --output PATH                 Output CSV path [${OUT}].
  --log-dir DIR                 Per-run log directory [${LOG_DIR}].
  --r-file PATH                 Load R from file instead of generating it.
  --s-file PATH                 Load S from file instead of generating it.
  --no-basic-numa               Do not pass --basic-numa to mchashjoins.
  --enable-key8b                Build 16-byte tuples instead of default 8-byte tuples.
  --allow-generated-overflow    Do not abort if generated payloads exceed width.
  -h, --help                    Show this help.

Environment overrides:
  THREADS, PAYLOAD_WIDTHS, RADIX_BITS_LIST, NUM_PASSES, OUT, LOG_DIR,
  BUILD_LOG, BASIC_NUMA, KEY8B

CSV fields:
  algo,payload_width,radix_bits,threads,throughput_mtps,time_ms,
  vector_total_bytes,extra_space_ratio,status,stdout_log,stderr_log
EOF
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --run)
      RUN=1
      shift
      ;;
    --dry-run)
      RUN=0
      shift
      ;;
    --threads)
      THREADS="$2"
      shift 2
      ;;
    --r-size)
      R_SIZE="$2"
      shift 2
      ;;
    --s-size)
      S_SIZE="$2"
      shift 2
      ;;
    --payload-widths)
      PAYLOAD_WIDTHS="$2"
      shift 2
      ;;
    --radix-bits)
      RADIX_BITS_LIST="$2"
      shift 2
      ;;
    --num-passes)
      NUM_PASSES="$2"
      shift 2
      ;;
    --output)
      OUT="$2"
      shift 2
      ;;
    --log-dir)
      LOG_DIR="$2"
      shift 2
      ;;
    --r-file)
      R_FILE="$2"
      shift 2
      ;;
    --s-file)
      S_FILE="$2"
      shift 2
      ;;
    --no-basic-numa)
      BASIC_NUMA=0
      shift
      ;;
    --enable-key8b)
      KEY8B=1
      shift
      ;;
    --allow-generated-overflow)
      ALLOW_GENERATED_OVERFLOW=1
      shift
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      echo "[ERROR] Unknown option: $1" >&2
      usage >&2
      exit 2
      ;;
  esac
done

payload_max_for_width() {
  case "$1" in
    1) echo 255 ;;
    2) echo 65535 ;;
    4) echo 4294967295 ;;
    *)
      echo "[ERROR] payload width must be one of 1, 2, or 4: $1" >&2
      exit 2
      ;;
  esac
}

tuple_bytes() {
  if [[ "$KEY8B" -eq 1 ]]; then
    echo 16
  else
    echo 8
  fi
}

print_plan() {
  echo "PRVJ tuning plan"
  echo "  repo: ${ROOT_DIR}"
  echo "  mode: $([[ "$RUN" -eq 1 ]] && echo run || echo dry-run)"
  echo "  R_SIZE: ${R_SIZE}"
  echo "  S_SIZE: ${S_SIZE}"
  echo "  THREADS: ${THREADS}"
  echo "  PAYLOAD_WIDTHS: ${PAYLOAD_WIDTHS}"
  echo "  RADIX_BITS_LIST: ${RADIX_BITS_LIST}"
  echo "  NUM_PASSES: ${NUM_PASSES}"
  echo "  BASIC_NUMA: ${BASIC_NUMA}"
  echo "  KEY8B: ${KEY8B}"
  echo "  OUT: ${OUT}"
  echo "  LOG_DIR: ${LOG_DIR}"
  if [[ -n "$R_FILE" || -n "$S_FILE" ]]; then
    echo "  R_FILE: ${R_FILE:-<unset>}"
    echo "  S_FILE: ${S_FILE:-<unset>}"
  else
    echo "  input: generated by mchashjoins"
  fi
  echo
  echo "Matrix:"
  for radix_bits in ${RADIX_BITS_LIST}; do
    for payload_width in ${PAYLOAD_WIDTHS}; do
      echo "  radix_bits=${radix_bits} payload_width=${payload_width}"
    done
  done
}

validate_inputs() {
  if [[ -n "$R_FILE" || -n "$S_FILE" ]]; then
    if [[ -z "$R_FILE" || -z "$S_FILE" ]]; then
      echo "[ERROR] --r-file and --s-file must be provided together." >&2
      exit 2
    fi
    if [[ ! -r "$R_FILE" ]]; then
      echo "[ERROR] R file is not readable: $R_FILE" >&2
      exit 2
    fi
    if [[ ! -r "$S_FILE" ]]; then
      echo "[ERROR] S file is not readable: $S_FILE" >&2
      exit 2
    fi
    return
  fi

  # VJ/PRVJ payload-width now models compressed payload storage. Generated
  # payloads may exceed the physical width and are stored in truncated form.
}

configure_for_radix_bits() {
  local radix_bits="$1"
  local configure_key_arg="--disable-key8B"

  if [[ "$KEY8B" -eq 1 ]]; then
    configure_key_arg="--enable-key8B"
  fi

  {
    echo "=== $(date -Iseconds) build radix_bits=${radix_bits} num_passes=${NUM_PASSES} ==="
    if [[ -f Makefile ]]; then
      make distclean
    fi
    ./configure "${configure_key_arg}" \
      CPPFLAGS="-DNUM_PASSES=${NUM_PASSES} -DNUM_RADIX_BITS=${radix_bits}"
    make
  } >>"${BUILD_LOG}" 2>&1
}

run_one() {
  local radix_bits="$1"
  local payload_width="$2"
  local stdout_log="$LOG_DIR/prvj_rb${radix_bits}_pw${payload_width}.stdout"
  local stderr_log="$LOG_DIR/prvj_rb${radix_bits}_pw${payload_width}.stderr"
  local status="OK"
  local numa_args=()
  local data_args=(-r "$R_SIZE" -s "$S_SIZE")

  if [[ "$BASIC_NUMA" -eq 1 ]]; then
    numa_args+=(--basic-numa)
  fi

  if [[ -n "$R_FILE" ]]; then
    data_args+=(-R "$R_FILE" -S "$S_FILE")
  fi

  if ! "$ROOT_DIR/src/mchashjoins" \
      -a "$ALGO" \
      -n "$THREADS" \
      "${data_args[@]}" \
      "${numa_args[@]}" \
      --payload-width="$payload_width" \
      >"$stdout_log" 2>"$stderr_log"; then
    status="FAIL"
  fi

  local timing_line stats_line time_usec time_ms throughput_mtps
  local vector_total_bytes extra_space_ratio raw_bytes tuple_size

  timing_line="$(awk -F',' '/^[[:space:]]*[0-9]+[[:space:]]*,[[:space:]]*[0-9]+[[:space:]]*,/ { line=$0 } END { print line }' "$stdout_log")"
  stats_line="$(awk -F',' '/^PRVJ_STATS_CSV,/ { line=$0 } END { print line }' "$stdout_log")"

  time_usec=""
  time_ms=""
  throughput_mtps=""
  vector_total_bytes=""
  extra_space_ratio=""

  if [[ -n "$timing_line" ]]; then
    time_usec="$(awk -F',' '{ gsub(/[[:space:]]/, "", $6); print $6 }' <<<"$timing_line")"
    time_ms="$(awk -v usec="$time_usec" 'BEGIN { if (usec > 0) printf "%.3f", usec / 1000.0 }')"
    throughput_mtps="$(awk -v s="$S_SIZE" -v usec="$time_usec" 'BEGIN { if (usec > 0) printf "%.6f", s / usec }')"
  fi

  if [[ -n "$stats_line" ]]; then
    vector_total_bytes="$(awk -F',' '{ gsub(/[[:space:]]/, "", $3); print $3 }' <<<"$stats_line")"
    tuple_size="$(tuple_bytes)"
    raw_bytes=$(( (R_SIZE + S_SIZE) * tuple_size ))
    extra_space_ratio="$(awk -v extra="$vector_total_bytes" -v raw="$raw_bytes" 'BEGIN { if (raw > 0 && extra != "") printf "%.8f", extra / raw }')"
  fi

  printf '%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s\n' \
    "$ALGO" "$payload_width" "$radix_bits" "$THREADS" \
    "$throughput_mtps" "$time_ms" "$vector_total_bytes" "$extra_space_ratio" \
    "$status" "$stdout_log" "$stderr_log" >>"$OUT"
}

cd "$ROOT_DIR"
print_plan

if [[ "$RUN" -ne 1 ]]; then
  cat <<EOF

Dry-run only. No build or experiment was started.
Run with --run when the input payloads are compatible with the selected widths.
EOF
  exit 0
fi

validate_inputs
mkdir -p "$LOG_DIR"

echo "algo,payload_width,radix_bits,threads,throughput_mtps,time_ms,vector_total_bytes,extra_space_ratio,status,stdout_log,stderr_log" >"$OUT"

for radix_bits in ${RADIX_BITS_LIST}; do
  echo "[INFO] Building NUM_RADIX_BITS=${radix_bits}, NUM_PASSES=${NUM_PASSES}" >&2
  configure_for_radix_bits "$radix_bits"
  for payload_width in ${PAYLOAD_WIDTHS}; do
    echo "[INFO] Running ${ALGO}: radix_bits=${radix_bits}, payload_width=${payload_width}" >&2
    run_one "$radix_bits" "$payload_width"
  done
done

echo "[INFO] Output CSV: $OUT" >&2
echo "[INFO] Build log: $BUILD_LOG" >&2
echo "[INFO] Run logs: $LOG_DIR" >&2
